"""
title: QuizUI
author: Axel Chamberland
git_url: https://github.com/axel-chamberland/OpenQuizUI
description: This tool gives an interface for quizzes generated by large language model.
required_open_webui_version: 0.9.2
version: 0.0.1
licence: MIT
"""

from pydantic import BaseModel, Field
from fastapi.responses import HTMLResponse
import json


class Tools:
    def __init__(self):
        """Initialize the Tool."""
        self.valves = self.Valves()

    class Valves(BaseModel):
        shuffle_options: bool = Field(
            default=True,
            description="Wether or not to use the choice order from the llm or to make it random",
        )

    async def generate_quiz(self, title, questions_and_answers: list[dict]):
        """
        Generate a multiple-choice quiz.

        Args:
            title (str):
                The title of the quiz.

            questions (list[dict]):
                A list of question objects.

                Each question dictionary must contain:
                    - "id" (str):
                        Unique question identifier.

                    - "question" (str):
                        The question text.

                    - "options" (list[str]):
                        List of answer choices.

                    - "correct_index" (int):
                        Zero-based index of the correct answer
                        inside the options list.

        Returns:
            Generated quiz accessible to the user,
            or an error message.
        """

        if self.valves.shuffle_options:
            shuffle_options(questions_and_answers)

        quiz = generate_quiz_dict(title, questions_and_answers)

        return HTMLResponse(
            content=wrap_html(quiz),
            headers={"Content-Disposition": "inline"},
        )


def generate_quiz_dict(title, questions):
    quiz = {"title": title, "questions": questions}

    return quiz


def wrap_html(quiz):
    quiz_json = json.dumps(quiz)
    return f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <title>Quiz</title>
        <style>
        {style}
        </style>
        </head>
        <body>
        <div id="app">
            <div class="question-box">
            <h1>Biology Quiz (1/5)</h1>
            <p id="question">What is the powerhouse of the cell?</p>
            <div id="options"></div>
            <div id="navigation">
            <button id="prevButton" disabled>Previous</button>
            <button id="revealButton">Reveal Answer</button>
            <button id="nextButton" disabled>Next</button>
            </div>
                </div>
        </div>

        <script>
        const quiz = {quiz_json}
        {script}
        </script>
        </body>
        </html>
        """


def shuffle_options(questions: list[dict]):
    import random

    for question in questions:
        choices = question["options"]

        indices = [x for x in range(len(question["options"]))]
        random.shuffle(indices)

        shuffled_options = []
        new_correct_index = None
        for new_idx, old_idx in enumerate(indices):
            shuffled_options.append(choices[old_idx])
            if old_idx == question["correct_index"]:
                new_correct_index = new_idx

        question["options"] = shuffled_options
        question["correct_index"] = new_correct_index


"""
OpenWebUI default color scheme:
    --color-gray-50: oklch(98% 0 0);
    --color-gray-100: oklch(94% 0 0);
    --color-gray-200: oklch(92% 0 0);
    --color-gray-300: oklch(85% 0 0);
    --color-gray-400: oklch(77% 0 0);
    --color-gray-500: oklch(69% 0 0);
    --color-gray-600: oklch(51% 0 0);
    --color-gray-700: oklch(42% 0 0);
    --color-gray-800: oklch(32% 0 0);
    --color-gray-900: oklch(20% 0 0);
    --color-gray-950: oklch(16% 0 0);
"""

style = """
:root {
    color-scheme: light dark;

    --bg: oklch(100% 0 0);
    --btn: oklch(94% 0 0);
    --text: oklch(20% 0 0);
    --border: oklch(85% 0 0);

    --surface: color-mix(in srgb, var(--bg) 92%, var(--text) 8%);
    --surface-2: color-mix(in srgb, var(--bg) 96%, var(--text) 4%);

    --success: #00c853;
    --danger: #dc3545;
}

@media (prefers-color-scheme: dark) {
    :root {
        --bg: oklch(20% 0 0);
        --btn: oklch(20% 0 0);
        --text: oklch(94% 0 0);
        --border: oklch(85% 0 0);

        --surface: color-mix(in srgb, var(--bg) 92%, var(--text) 8%);
        --surface-2: color-mix(in srgb, var(--bg) 85%, var(--bg) 15%);
    }
}


body {
    margin: 0;
    padding: 0;
    background: var(--bg);
}

.question-box {
    padding: 2rem;
    background: var(--bg);
    color: var(--text);
}

#question {
    margin-bottom: 2em;
    font-size: 1.1rem;
}

#options {-webkit-appearance: none;
    display: grid;
    gap: 0.75rem;
    margin-bottom: 2em;
    padding: 0 1.5rem;
}

.option {
    padding: 1rem;
    font-size: 1.1rem;
    border: 1px solid;
    border-color: var(--border);
    border-radius: 0.25rem;
    background: var(--btn);
    cursor: pointer;
    text-align: center;
    color: var(--text)
}

.option:hover {
    filter: brightness(1.5);
}

.option.correct {
    background: color-mix(in srgb, var(--success) 30%, var(--surface));
    border-color: var(--success);
}

.option.wrong {
    background: color-mix(in srgb, var(--danger) 30%, var(--surface));
    border-color: var(--danger);
}

#navigation {
    display: flex;
    justify-content: center;
    gap: 0.5rem;
    margin-top: 2rem;
}

"""

script = """
// Height reporting script
function reportHeight() {
  const h = document.documentElement.scrollHeight;
  parent.postMessage({ type: 'iframe:height', height: h }, '*');
}
window.addEventListener('load', reportHeight);
new ResizeObserver(reportHeight).observe(document.body);

let currentQuestionIndex = 0;
let wrongAnswerCount = 0;

function renderQuiz() {
  const questionBox = document.querySelector(".question-box");
  const questionBoxTitle = questionBox.querySelector("h1");
  const questionText = questionBox.querySelector("#question");
  const optionsContainer = document.getElementById("options");
  const navigationContainer = questionBox.querySelector("#navigation");

  // Update question
  questionBoxTitle.textContent = `${quiz.title} (${currentQuestionIndex + 1}/${quiz.questions.length})`;
  questionText.textContent = quiz.questions[currentQuestionIndex].question;

  // Clear and rebuild options
  optionsContainer.innerHTML = '';
  wrongAnswerCount = 0; // Answer button is revealed when user exhausted all options

  const currentQuestion = quiz.questions[currentQuestionIndex];

  currentQuestion.options.forEach((option, index) => {
    const button = document.createElement("button");
    button.textContent = option;
    button.className = 'option'

    button.addEventListener("click", () => {
      if (index === currentQuestion.correct_index) {
        button.classList.add('correct');
        button.disabled = true;
        const allButtons = document.querySelectorAll('.option');
        allButtons.forEach(btn => btn.disabled = true);
      } else {
        button.classList.add('wrong');
        button.disabled = true;
        wrongAnswerCount++;
        const totalOptions = currentQuestion.options.length;
        if (wrongAnswerCount === totalOptions - 1) {
          revealAnswer();
          button.disabled = true;
        }
      }
    });

    optionsContainer.appendChild(button);
  });

  // Update button states
  const prevButton = navigationContainer.querySelector("#prevButton");
  const nextButton = navigationContainer.querySelector("#nextButton");

  prevButton.disabled = currentQuestionIndex === 0;
  nextButton.disabled = currentQuestionIndex === quiz.questions.length - 1;
}

function nextQuestion() {
  if (currentQuestionIndex + 1 < quiz.questions.length) {
    currentQuestionIndex++
    renderQuiz();
  } else {
    renderQuiz();
  }
}

function revealAnswer() {
  const currentQuestion = quiz.questions[currentQuestionIndex];
  const optionsContainer = document.getElementById("options");

  // Get all buttons in the current question
  const buttons = optionsContainer.querySelectorAll("button");

  // Find and highlight the correct answer
  buttons.forEach(button => {
    const buttonIndex = Array.from(buttons).indexOf(button);
    if (buttonIndex === currentQuestion.correct_index) {
      button.classList.add('correct');
    }
  });
}

// Handle navigation buttons
const nextButton = document.getElementById("nextButton");
nextButton.addEventListener("click", nextQuestion);

const prevButton = document.getElementById("prevButton");
prevButton.addEventListener("click", () => {
  currentQuestionIndex = Math.max(0, currentQuestionIndex - 1);
  renderQuiz();
});

const revealButton = document.getElementById("revealButton");
revealButton.addEventListener("click", revealAnswer);

renderQuiz();
"""
