"""
title: QuizUI
author: Axel Chamberland
git_url: https://github.com/axel-chamberland/OpenQuizUI
description: This tool gives an interface for quizzes generated by large language model.
version: 2.0.1
licence: MIT
"""

import json
import random
from difflib import SequenceMatcher
from functools import wraps

from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

THEMES = {
    "default_light": """
--bg: oklch(100% 0 0);
--btn: oklch(94% 0 0);
--text: oklch(20% 0 0);
--border: oklch(85% 0 0);

--success: #0fff93;
--danger: #ff4545;
--skipped: #ffb800;
--unanswered: #8a8a8a;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "default_dark": """
--bg: oklch(20% 0 0);
--btn: oklch(24% 0 0);
--text: oklch(94% 0 0);
--border: oklch(85% 0 0);

--success: #00ff00;
--danger: #ff0000;
--skipped: #ffcc00;
--unanswered: #999999;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "tokyonight": """
--bg: #1a1b26;
--btn: #242b42;
--text: #c0caf5;
--border: #7aa2f7;

--success: #1abc9c;
--danger: #ff007c;
--skipped: #e0af68;
--unanswered: #565f89;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "high_contrast": """
--bg: #000000;
--btn: #111111;
--text: #ffffff;
--border: #ffffff;

--success: #00ff00;
--danger: #ff0000;
--skipped: #ffff00;
--unanswered: #00ffff;

--correct_bg: color-mix(in srgb, var(--success) 40%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 40%, var(--btn));
""",
    "soft_pastel": """
--bg: #fdf6f0;
--btn: #f2e9e4;
--text: #4a4a4a;
--border: #d8cfc4;

--success: #6bbf59;
--danger: #e07a5f;
--skipped: #e6b566;
--unanswered: #a8998e;

--correct_bg: color-mix(in srgb, var(--success) 25%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 25%, var(--btn));
""",
}


class Tools:
    class Valves(BaseModel):
        enable_mathjax: bool = Field(
            default=False,
            description="Disabled by default for privacy and performance. Enable LaTeX/math rendering with MathJax. Requires Internet access to load the MathJax library from a CDN. When disabled or offline, LaTeX expressions are displayed as plain text.",
        )
        enable_explanations: bool = Field(
            default=False,
            description="Instructs the model to include an explanations for each question. Disabled by default as it requires the models to generate extra content.",
        )
        dark_mode: int = Field(
            default=-1,
            description="-1: Let browser decide. 0: Light mode. 1: Dark mode",
        )
        light_theme: str = Field(
            default="default_light",
            description="change the dark mode theme to a different theme. to define a new theme, you can add a theme at the top of the code where the templates are. Defaults: default_light, soft_pastel",
        )
        dark_theme: str = Field(
            default="default_dark",
            description="change the dark mode theme to a different theme. to define a new theme, you can add a theme at the top of the code where the templates are. Defaults: default_dark. high_contrast, tokyonight",
        )

    def __init__(self):
        self.valves = self.Valves()

    # This function adds to the docstring of generate_quiz for extra optional instructions
    def __getattribute__(self, name):
        if name == "generate_quiz":
            original = object.__getattribute__(
                self, "generate_quiz"
            )  # same name, no recursion
            valves = object.__getattribute__(self, "valves")

            @wraps(original)
            async def generate_quiz(*args, **kwargs):
                return await original(*args, **kwargs)

            doc = original.__doc__ or ""
            if valves.enable_explanations:
                doc += """

        Additional requirement:
            Each question dict MUST also include an "explanation" (str) key —
            a concise explanation of why the correct answer is correct, written
            to teach the underlying concept.
        """
            generate_quiz.__doc__ = doc
            return generate_quiz

        return object.__getattribute__(self, name)

    async def generate_quiz(self, title, questions: list[dict]):
        """
        Generate a multiple-choice quiz and display it to the user.

        Args:
            title (str):
                The title of the quiz.

            questions (list[dict]):
                A list of question objects. Each dictionary MUST contain
                these three keys:
                    - "question"    (str)       The question text.
                    - "answer"      (str)       The single CORRECT answer,
                                                 written out in full.
                    - "distractors" (list[str]) 1 or more WRONG answers.
                                                 Do not include the correct
                                                 answer in this list.

                Example of one valid item:
                    {
                        "question": "What is the capital of France?",
                        "answer": "Paris",
                        "distractors": ["Berlin", "Rome", "Madrid"]
                    }

                Write the answer only once, in "answer" — do not also
                repeat it inside "distractors". Do not rename any key.
                Every item must follow this exact structure or the quiz
                will fail to generate.

        Returns:
            Generated quiz accessible to the user,
            or an error message.
        """
        try:
            questions_and_answers, warnings = normalize_questions(questions)

            if not questions_and_answers:
                error_report = "\n".join(f"- {w}" for w in warnings)
                return (
                    "The quiz could not be generated because no valid "
                    "questions could be recovered from 'questions':\n\n"
                    f"{error_report}\n\n"
                    "Please regenerate the JSON. Each item needs 'question' "
                    "(string), 'answer' (string, the correct answer), and "
                    "'distractors' (a list of at least 1 wrong answer)."
                )

            shuffle_options(questions_and_answers)

            quiz = {"title": title, "questions": questions_and_answers}

            # Modify Theme

            option_dark = self.valves.dark_theme
            option_light = self.valves.light_theme

            if self.valves.dark_mode == 0:
                option_dark = option_light
            elif self.valves.dark_mode == 1:
                option_light = option_dark

            dark_theme = THEMES.get(option_dark, THEMES["default_dark"])
            light_theme = THEMES.get(option_light, THEMES["default_light"])

            # Generate quiz
            content = wrap_html(
                quiz, self.valves.enable_mathjax, light_theme, dark_theme
            )
            return HTMLResponse(
                content=content,
                headers={"Content-Disposition": "inline"},
            )

        except Exception as e:
            return f"An unexpected error occurred: {e}"


# =========================
# NORMALIZATION
# =========================

# Accepted synonyms for each field, since weaker models often use a
# slightly different key name than the one requested.
_QUESTION_KEYS = ("question", "q", "prompt", "text")
_ANSWER_KEYS = ("answer", "correct", "correct_answer", "correct_option")
_DISTRACTOR_KEYS = (
    "distractors",
    "wrong_answers",
    "incorrect_answers",
    "wrong_options",
)
_OPTIONS_KEYS = ("options", "choices", "answers", "choices_list")
_INDEX_KEYS = ("correct_index", "answer_index", "index", "correctIndex")
_EXPLANATION_KEYS = ("explanation", "rationale", "why", "reason")


def _first_present(d: dict, keys, expected_type=None):
    for k in keys:
        if k in d:
            v = d[k]
            if expected_type is None or isinstance(v, expected_type):
                return v
    return None


def _best_match_index(answer_text: str, options: list) -> int | None:
    """Find which option the model's free-text answer refers to.

    Tries exact (case-insensitive) match first, then substring match,
    then falls back to the closest fuzzy match so small wording
    differences ("Paris." vs "Paris") don't cause a hard failure.
    """
    if not isinstance(answer_text, str):
        return None

    norm_answer = answer_text.strip().lower().rstrip(".")
    norm_options = [str(o).strip().lower().rstrip(".") for o in options]

    if norm_answer in norm_options:
        return norm_options.index(norm_answer)

    for i, o in enumerate(norm_options):
        if norm_answer in o or o in norm_answer:
            return i

    best_i, best_score = None, 0.0
    for i, o in enumerate(norm_options):
        score = SequenceMatcher(None, norm_answer, o).ratio()
        if score > best_score:
            best_i, best_score = i, score

    return best_i if best_score >= 0.6 else None


def normalize_questions(questions) -> tuple[list[dict], list[str]]:
    """
    Best-effort cleanup of whatever the model produced.

    Returns (normalized_questions, warnings). Items that can't be
    salvaged are skipped (with a warning) rather than aborting the
    whole quiz — one bad question shouldn't sink the other nine.
    """
    warnings: list[str] = []

    if not isinstance(questions, list):
        return [], [
            f"'questions' must be a list of question objects, got "
            f"'{type(questions).__name__}'."
        ]

    normalized = []

    for i, q in enumerate(questions):
        label = f"Question at position {i}"

        if not isinstance(q, dict):
            warnings.append(f"{label} is not an object — skipped.")
            continue

        question_text = _first_present(q, _QUESTION_KEYS)

        if question_text is None:
            warnings.append(f"{label} is missing question text — skipped.")
            continue

        question_text = str(question_text)

        if not question_text.strip():
            warnings.append(f"{label} is missing question text — skipped.")
            continue

        options = None
        correct_index = None

        # --- Preferred path: answer + distractors -------------------
        # No text-matching needed here: we build the option list
        # ourselves, so the correct answer can't fail to line up with
        # itself the way it could when the model had to repeat it
        # verbatim inside an "options" array.
        answer_text = _first_present(q, _ANSWER_KEYS)

        if answer_text is not None:
            answer_text = str(answer_text)

        distractors = _first_present(q, _DISTRACTOR_KEYS, list)

        if answer_text and distractors:
            distractors = [str(d) for d in distractors if str(d).strip()]
            # Guard against the model accidentally repeating the
            # answer inside distractors too (ignoring case/punctuation
            # so "Paris." doesn't slip past "Paris").
            norm_answer = answer_text.strip().lower().rstrip(".")
            distractors = [
                d for d in distractors if d.strip().lower().rstrip(".") != norm_answer
            ]
            if distractors:
                options = [answer_text] + distractors
                correct_index = 0

        if options is None or correct_index is None:
            warnings.append(
                f"{label} ('{question_text[:40]}...') — could not determine "
                f"a valid answer and distractors — skipped."
            )
            continue

        explanation = _first_present(q, _EXPLANATION_KEYS)
        if explanation is not None:
            explanation = str(explanation).strip() or None

        item = {
            "id": q.get("id") or f"q{i + 1}",
            "question": question_text,
            "options": options,
            "correct_index": correct_index,
        }
        if explanation:
            item["explanation"] = explanation

        normalized.append(item)

    return normalized, warnings


# =========================
# QUIZ LOGIC
# =========================


def shuffle_options(questions: list[dict]):

    for question in questions:
        choices = question["options"]

        indices = list(range(len(choices)))
        random.shuffle(indices)

        shuffled_options = []
        new_correct_index = None
        for new_idx, old_idx in enumerate(indices):
            shuffled_options.append(choices[old_idx])
            if old_idx == question["correct_index"]:
                new_correct_index = new_idx

        question["options"] = shuffled_options
        question["correct_index"] = new_correct_index


# =========================
# HTML WRAPPER
# =========================


def wrap_html(
    quiz, enable_mathjax: bool, light_theme="default_light", dark_theme="default_dark"
):
    return "__HTML_PLACEHOLDER__"
