"""
title: QuizUI
author: Axel Chamberland
git_url: https://github.com/axel-chamberland/OpenQuizUI
description: This tool gives an interface for quizzes generated by large language model.
version: 1.0
licence: MIT
"""

from pydantic import BaseModel, Field
from fastapi.responses import HTMLResponse
from difflib import SequenceMatcher
import json
import random


THEMES = {
    "default_light": """
--bg: oklch(100% 0 0);
--btn: oklch(94% 0 0);
--text: oklch(20% 0 0);
--border: oklch(85% 0 0);

--success: #0fff93;
--danger: #ff4545;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "default_dark": """
--bg: oklch(20% 0 0);
--btn: oklch(24% 0 0);
--text: oklch(94% 0 0);
--border: oklch(85% 0 0);

--success: #00ff00;
--danger: #ff0000;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "tokyonight": """
--bg: #1a1b26;
--btn: #242b42;
--text: #c0caf5;
--border: #7aa2f7;

--success: #1abc9c;
--danger: #ff007c;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "high_contrast": """
--bg: #000000;
--btn: #111111;
--text: #ffffff;
--border: #ffffff;

--success: #00ff00;
--danger: #ff0000;

--correct_bg: color-mix(in srgb, var(--success) 40%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 40%, var(--btn));
""",
    "soft_pastel": """
--bg: #fdf6f0;
--btn: #f2e9e4;
--text: #4a4a4a;
--border: #d8cfc4;

--success: #6bbf59;
--danger: #e07a5f;

--correct_bg: color-mix(in srgb, var(--success) 25%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 25%, var(--btn));
""",
}


class Tools:
    def __init__(self):
        """Initialize the Tool."""
        self.valves = self.Valves()

    class Valves(BaseModel):
        enable_mathjax: bool = Field(
            default=False,
            description="Disabled by default for privacy and performance. Enable LaTeX/math rendering with MathJax. Requires Internet access to load the MathJax library from a CDN. When disabled or offline, LaTeX expressions are displayed as plain text.",
        )

        dark_mode: int = Field(
            default=-1,
            description="-1: Let browser decide. 0: Light mode. 1: Dark mode",
        )
        light_theme: str = Field(
            default="default_light",
            description="change the dark mode theme to a different theme. to define a new theme, you can add a theme at the top of the code where the templates are. Defaults: default_light, soft_pastel",
        )
        dark_theme: str = Field(
            default="default_dark",
            description="change the dark mode theme to a different theme. to define a new theme, you can add a theme at the top of the code where the templates are. Defaults: default_dark. high_contrast, tokyonight",
        )

    async def generate_quiz(self, title, questions: list[dict]):
        """
        Generate a multiple-choice quiz and display it to the user.

        Args:
            title (str):
                The title of the quiz.

            questions (list[dict]):
                A list of question objects. Each dictionary MUST contain
                these three keys:
                    - "question"    (str)       The question text.
                    - "answer"      (str)       The single CORRECT answer,
                                                 written out in full.
                    - "distractors" (list[str]) 1 or more WRONG answers.
                                                 Do not include the correct
                                                 answer in this list.

                Example of one valid item:
                    {
                        "question": "What is the capital of France?",
                        "answer": "Paris",
                        "distractors": ["Berlin", "Rome", "Madrid"]
                    }

                Write the answer only once, in "answer" — do not also
                repeat it inside "distractors". Do not rename any key.
                Every item must follow this exact structure or the quiz
                will fail to generate.

        Returns:
            Generated quiz accessible to the user,
            or an error message.
        """
        try:
            questions_and_answers, warnings = normalize_questions(questions)

            if not questions_and_answers:
                error_report = "\n".join(f"- {w}" for w in warnings)
                return (
                    "The quiz could not be generated because no valid "
                    "questions could be recovered from 'questions':\n\n"
                    f"{error_report}\n\n"
                    "Please regenerate the JSON. Each item needs 'question' "
                    "(string), 'answer' (string, the correct answer), and "
                    "'distractors' (a list of at least 1 wrong answer)."
                )

            shuffle_options(questions_and_answers)

            quiz = {"title": title, "questions": questions_and_answers}

            # Modify Theme

            option_dark = self.valves.dark_theme
            option_light = self.valves.light_theme

            if self.valves.dark_mode == 0:
                option_dark = option_light
            elif self.valves.dark_mode == 1:
                option_light = option_dark

            dark_theme = THEMES.get(option_dark, THEMES["default_dark"])
            light_theme = THEMES.get(option_light, THEMES["default_light"])

            # Generate quiz
            content = wrap_html(
                quiz, self.valves.enable_mathjax, light_theme, dark_theme
            )
            return HTMLResponse(
                content=content,
                headers={"Content-Disposition": "inline"},
            )

        except Exception as e:
            return f"An unexpected error occurred: {e}"


# =========================
# NORMALIZATION
# =========================

# Accepted synonyms for each field, since weaker models often use a
# slightly different key name than the one requested.
_QUESTION_KEYS = ("question", "q", "prompt", "text")
_ANSWER_KEYS = ("answer", "correct", "correct_answer", "correct_option")
_DISTRACTOR_KEYS = (
    "distractors",
    "wrong_answers",
    "incorrect_answers",
    "wrong_options",
)
_OPTIONS_KEYS = ("options", "choices", "answers", "choices_list")
_INDEX_KEYS = ("correct_index", "answer_index", "index", "correctIndex")


def _first_present(d: dict, keys, expected_type=None):
    for k in keys:
        if k in d:
            v = d[k]
            if expected_type is None or isinstance(v, expected_type):
                return v
    return None


def _best_match_index(answer_text: str, options: list) -> int | None:
    """Find which option the model's free-text answer refers to.

    Tries exact (case-insensitive) match first, then substring match,
    then falls back to the closest fuzzy match so small wording
    differences ("Paris." vs "Paris") don't cause a hard failure.
    """
    if not isinstance(answer_text, str):
        return None

    norm_answer = answer_text.strip().lower().rstrip(".")
    norm_options = [str(o).strip().lower().rstrip(".") for o in options]

    if norm_answer in norm_options:
        return norm_options.index(norm_answer)

    for i, o in enumerate(norm_options):
        if norm_answer in o or o in norm_answer:
            return i

    best_i, best_score = None, 0.0
    for i, o in enumerate(norm_options):
        score = SequenceMatcher(None, norm_answer, o).ratio()
        if score > best_score:
            best_i, best_score = i, score

    return best_i if best_score >= 0.6 else None


def normalize_questions(questions) -> tuple[list[dict], list[str]]:
    """
    Best-effort cleanup of whatever the model produced.

    Returns (normalized_questions, warnings). Items that can't be
    salvaged are skipped (with a warning) rather than aborting the
    whole quiz — one bad question shouldn't sink the other nine.
    """
    warnings: list[str] = []

    if not isinstance(questions, list):
        return [], [
            f"'questions' must be a list of question objects, got "
            f"'{type(questions).__name__}'."
        ]

    normalized = []

    for i, q in enumerate(questions):
        label = f"Question at position {i}"

        if not isinstance(q, dict):
            warnings.append(f"{label} is not an object — skipped.")
            continue

        question_text = _first_present(q, _QUESTION_KEYS)

        if question_text is None:
            warnings.append(f"{label} is missing question text — skipped.")
            continue

        question_text = str(question_text)

        if not question_text.strip():
            warnings.append(f"{label} is missing question text — skipped.")
            continue

        options = None
        correct_index = None

        # --- Preferred path: answer + distractors -------------------
        # No text-matching needed here: we build the option list
        # ourselves, so the correct answer can't fail to line up with
        # itself the way it could when the model had to repeat it
        # verbatim inside an "options" array.
        answer_text = _first_present(q, _ANSWER_KEYS)

        if answer_text is not None:
            answer_text = str(answer_text)

        distractors = _first_present(q, _DISTRACTOR_KEYS, list)

        if answer_text and distractors:
            distractors = [str(d) for d in distractors if str(d).strip()]
            # Guard against the model accidentally repeating the
            # answer inside distractors too (ignoring case/punctuation
            # so "Paris." doesn't slip past "Paris").
            norm_answer = answer_text.strip().lower().rstrip(".")
            distractors = [
                d for d in distractors if d.strip().lower().rstrip(".") != norm_answer
            ]
            if distractors:
                options = [answer_text] + distractors
                correct_index = 0

        if options is None or correct_index is None:
            warnings.append(
                f"{label} ('{question_text[:40]}...') — could not determine "
                f"a valid answer and distractors — skipped."
            )
            continue

        normalized.append(
            {
                "id": q.get("id") or f"q{i + 1}",
                "question": question_text,
                "options": options,
                "correct_index": correct_index,
            }
        )

    return normalized, warnings


# =========================
# QUIZ LOGIC
# =========================


def shuffle_options(questions: list[dict]):

    for question in questions:
        choices = question["options"]

        indices = list(range(len(choices)))
        random.shuffle(indices)

        shuffled_options = []
        new_correct_index = None
        for new_idx, old_idx in enumerate(indices):
            shuffled_options.append(choices[old_idx])
            if old_idx == question["correct_index"]:
                new_correct_index = new_idx

        question["options"] = shuffled_options
        question["correct_index"] = new_correct_index


# =========================
# HTML WRAPPER
# =========================


def wrap_html(quiz, enable_mathjax: bool, light_theme, dark_theme):
    quiz_json = json.dumps(quiz)

    rendered_script = script.replace(
        "__ENABLE_MATHJAX__", "true" if enable_mathjax else "false"
    )

    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Quiz</title>

<style>
{style.format(light_theme=light_theme, dark_theme=dark_theme)}
</style>
</head>

<body>
<div class="question-box">
    <div id="titleBar">
        <h1 id="title"></h1>
        <span id="timer">00:00</span>
    </div>
    <div id="navigation">
        <button id="revealButton" onclick="revealAnswer()">⌕</button>
        <button id="maximizeButton" onclick="toggleFullscreen()">⛶</button>
        <button id="downloadButton" onclick="downloadQuizHTML()">⤓</button>
        <button id="timerToggle" onclick="toggleTimer()">◷</button>

        <button id="prevButton" onclick="prevQuestion()">&lt</button>
        <div id="questionSelector">
            <input id="questionNumber" type="text" inputmode="numeric" value="1">
            <span class="separator">/</span>
            <span id="questionCount">1</span>
        </div>
        <button id="nextButton" onclick="nextQuestion()">&gt</button>
    </div>
    <p id="question"></p>
    <div id="options"></div>
</div>
<div id="results" style="display: none;">


    <div id="results-navigation">
        <!-- TODO
        <button onclick="reviewQuiz()">Review Quiz</button>
        -->
        <button onclick="prevQuestion()">↩</button>
        <button onclick="toggleFullscreen()">⛶</button>
        <button id="downloadButton" onclick="downloadQuizHTML()">⤓</button>
    </div>
    <div id="results-scroll">

        <div id="time"></div>
        <div id="averageTime"></div>

        <div id="statsChart"></div>
        <div class="stat-row">
            <div id="correct"></div>
            <div id="wrong"></div>
        </div>
        <div class="stat-row">
            <div id="unanswered"></div>
            <div id="skipped"></div>
        </div>

        <div class="stat-row">
            <div id="score"></div>
            <div id="accuracy"></div>
        </div>

        <button onclick="confirmRestart()">Restart</button>
        <div id="restart-confirm" style="display: none;">
            <span>Restart quiz?</span>
            <button onclick="restartQuiz()">Yes</button>
            <button onclick="cancelRestart()">No</button>
        </div>
    </div>




</div>


<script>
const quiz = {quiz_json};
{rendered_script}
</script>
<script>
{reportHeight}
</script>
</body>
</html>
"""


# =========================
# Height report script
# =========================

reportHeight = """
function reportHeight() {
    // Do not run when in fullscreen
    if (document.fullscreenElement) return;


    const questionBox = document.querySelector(".question-box");
    const results = document.getElementById("results");

    const visible = results.style.display !== "none"
        ? results
        : questionBox;

    const h = visible.scrollHeight;

    parent.postMessage({ type: "iframe:height", height: h }, "*");
}

window.addEventListener('load', reportHeight);

new ResizeObserver(reportHeight).observe(document.body);
"""

# =========================
# STYLE
# =========================

style = """
:root {{
    color-scheme: light dark;
{light_theme}
}}

@media (prefers-color-scheme: dark) {{
    :root {{
{dark_theme}
    }}
}}
* {{
    box-sizing: border-box;
    font-family: inherit;
}}
body {{
    background: var(--bg);
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    margin: 0;
}}

#titleBar {{
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
}}

#title {{
    margin: 0;
}}
.question-box {{
    display: flex;
    flex-direction: column;
    color: var(--text);
    width: min(800px, 100%);
    padding: 8px
}}

#question {{
    margin-bottom: 2em;
    font-size: 1.1rem;
}}

#options {{
    display: grid;
    grid-template-columns: 1;
    max-width: 100%;
    gap: 0.75rem;
    overflow-y: auto;
}}

button {{
    border: 1px solid;
    border-radius: 0.25rem;
    border-color: var(--border);
    background: var(--btn);
    cursor: pointer;
    text-align: center;
    color: var(--text);
    font-size: 1.1em;
}}
.option{{
    padding: 1rem 3rem 1rem 3rem;
    position: relative;
    text-align: center;
}}
button:disabled {{
    opacity: 0.4;
}}
.option:hover {{
    filter: contrast(1.1);
}}

.option.correct {{
    background: var(--correct_bg);
    border-color: var(--success);
    opacity: 1;
}}

.option.wrong {{
    background: var(--wrong_bg);
    border-color: var(--danger);
    opacity: 1;
}}


.option::after{{
    position: absolute;
    right: 1rem;
    top: 50%;
    transform: translateY(-50%);
    width: 1rem;
    text-align: center;
}}

.option.correct::after {{
    content: " ✓";
    font-weight: bold;
}}

.option.wrong::after {{
    content: " ✗";
    font-weight: bold;
}}

#navigation, #results-navigation {{

    display: flex;
    flex-wrap: nowrap;
    padding: 0.75rem;
    justify-content: center;
    gap: 0.5rem;

    z-index: 1000;
    border-bottom: 1px solid var(--border);
    margin-bottom: 20px;

    user-select: none;
    -webkit-user-select: none;
}}


#navigation button, #results-navigation button {{
    font-size : 2rem;


}}

#revealButton,
#maximizeButton,
#downloadButton,
#questionSelector {{
    flex: 0 0 auto;
    min-width: 2rem;
}}


#prevButton,
#nextButton {{
    flex: 1;
    font-size: clamp(1.5rem, 5vw, 2rem);
    max-width: 4rem;
}}


:fullscreen #navigation,
:fullscreen #results-navigation {{
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;

    margin-bottom: 0px;

    background: var(--bg);
    padding: 0.75rem;
    border-top: 1px solid var(--border);
    border-bottom: 0;
}}

:fullscreen .question-box {{
    padding-bottom: var(--nav-height);
}}

#questionSelector {{
    display: flex;
    align-items: center;
    white-space: nowrap;

    background: var(--btn);
    color: var(--text);

    border: 1px solid var(--border);
    border-radius: 0.25rem;

    font-size : 1.1rem;

    gap: 0.2rem;


}}


#questionNumber {{

    width: 3ch;
    text-align: center;
    font-size: 1.1rem;

    padding: 0;
    margin: 0;
    line-height: 1;

    background: transparent;
    color: var(--text);
    border: none;
    outline: none;

}}


#questionNumber:focus {{
    outline: none;
    border: none;
}}

#questionCount {{
    margin-right: 0.3em;
}}

mjx-container {{
    max-width: 100%;
    overflow-x: auto;
    white-space: normal;
}}

/* Hide timer by default */
#timer {{
    display: none;
    min-width: 4rem;
    font-size: 1.1rem;
    text-align: center;
    font-variant-numeric: tabular-nums;
}}
#timer.visible {{
    display: inline-block;
}}

#correct {{
    color: var(--success);
}}

#wrong {{
    color: var(--danger);
}}

#unanswered {{
    color: var(--unanswered);
}}

#skipped {{
    color: var(--skipped);
}}

.chart-correct   {{ stroke: var(--success); }}
.chart-wrong     {{ stroke: var(--danger); }}
.chart-unanswered{{ stroke: var(--unanswered); }}
.chart-skipped   {{ stroke: var(--skipped); }}

#results {{
    display: flex;
    flex-direction: column;
    width: 100%;
    height: 100vh;
}}

#results-scroll {{
    display: flex;
    flex-direction: column;
    gap: 1rem;
    width: 100%;
    max-width: min(90vw, 700px);
    max-height: 150vh;
    margin: 0 auto;
    padding: clamp(1rem, 4vw, 3rem);
    text-align: center;
    overflow-y: auto;
}}

.stat-row {{
    display: flex;
    gap: 1rem;
}}

.stat-row > div {{
    flex: 1;
    padding: 0.5rem;
    border-radius: 0.5rem;
    background: var(--btn);
}}

#statsChart {{
    height: min(50vh, 500px);
    align-self: center;
}}

#results-navigation {{
    display: flex;
    gap: 1rem;
    justify-content: center;
    margin: 8px;
}}
"""


# =========================
# SCRIPT (Front End)
# =========================

script = r"""
// Try to load math library (WARNING: requires internet)
const ENABLE_MATHJAX = __ENABLE_MATHJAX__;

let mathReady = false;

let wrongAnswerCount = 0;


let optionButtons = [];
let currentQuestion = null;

let answerRevealed = false;

// Timer
let timerVisible = false;
let timerStart = null;
let timerElapsed = 0;
let timerInterval = null;

// Stats
const UNANSWERED = 0;
const CORRECT = 1;
const WRONG = 2;
const SKIPPED = 3;
let questionResults = new Array(quiz.questions.length).fill(UNANSWERED);
let defaultStartDate = Date.now() // Default start date used if timer was never started
loadStats();

const timer = document.getElementById("timer");
const questionBox = document.querySelector(".question-box");
const questionText = questionBox.querySelector("#question");
const optionsContainer = document.getElementById("options");
const navigationContainer = questionBox.querySelector("#navigation");
const questionNumber = document.getElementById("questionNumber");
const results = document.getElementById("results");


// Update title
document.getElementById("title").textContent = quiz.title;

// Update max question count
const questionCount = document.getElementById("questionCount");

questionCount.textContent = quiz.questions.length;

let currentQuestionIndex = getStoredQuestionIndex();
questionNumber.value = currentQuestionIndex + 1;



window.MathJax = {
    tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']]
    }
};

function loadMathJax() {
    return new Promise((resolve) => {
        if (!ENABLE_MATHJAX) {
            mathReady = false;
            resolve(false);
            return;
        }

        const script = document.createElement("script");
        script.src = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js";

        script.onload = () => {
            mathReady = true;
            resolve(true);
        };

        script.onerror = () => {
            mathReady = false;
            resolve(false);
        };

        document.head.appendChild(script);
    });
}

// UI events

// Get height of navigation bar for CSS (fullscreen mode)
const nav = document.getElementById("navigation");

function updateNavHeight() {
    document.documentElement.style.setProperty(
        "--nav-height",
        `${nav.offsetHeight}px`
    );
}

updateNavHeight();
new ResizeObserver(updateNavHeight).observe(nav);
window.addEventListener("resize", updateNavHeight);


function toggleFullscreen() {
    const el = document.documentElement;

    if (!document.fullscreenElement) {
        el.requestFullscreen?.();
    } else {
        document.exitFullscreen?.();
    }
}

// Helpers

function renderMath(text) {
    if (!text) return "";

    return text.replace(/\$(.+?)\$/g, (match, expr) => {
        if (mathReady && window.MathJax) {
            return match;
        }
        return `<code>${expr}</code>`;
    });
}

function renderInlineMarkdown(text) {
    if (!text) return "";

    text = text
        .replace(/\*\*(.*?)\*\*/g, "<b>$1</b>")
        .replace(/\*(.*?)\*/g, "<i>$1</i>")

    return renderMath(text);
}

function renderMarkdown(text) {
    if (!text) return "";
    return renderInlineMarkdown(text).replace(/\n/g, "<br>");
}


async function renderQuiz() {
    const questionBox = document.querySelector(".question-box");
    const questionText = questionBox.querySelector("#question");
    const optionsContainer = document.getElementById("options");
    const navigationContainer = questionBox.querySelector("#navigation");

    if (!quiz.questions || quiz.questions.length === 0) {
        document.getElementById("question").textContent = "No valid questions parsed";
        return;
    }

    // Update question
    questionText.innerHTML = renderMarkdown(quiz.questions[currentQuestionIndex].question);

    // Clear and rebuild options
    optionsContainer.innerHTML = '';
    wrongAnswerCount = 0; // Answer button is revealed when user exhausted all options
    optionButtons = [];

    currentQuestion = quiz.questions[currentQuestionIndex];
    currentQuestion.options.forEach((option, index) => {
        const button = document.createElement("button");
        button.innerHTML = renderMarkdown(option);
        button.className = "option";

        optionButtons.push(button);

        button.addEventListener("click", () => {
            handleAnswer(index, button);
        });

        optionsContainer.appendChild(button);
    });
    // Update button states
    const prevButton = navigationContainer.querySelector("#prevButton");
    prevButton.disabled = currentQuestionIndex === 0;

    // Next button is not disabled as it goes to the result screen after last question
    // const nextButton = navigationContainer.querySelector("#nextButton");
    // nextButton.disabled = currentQuestionIndex === quiz.questions.length - 1;


    try {
        await MathJax.typesetPromise();
    } catch (err) {
        console.error(err);
    }



}

function nextQuestion() {
    if (currentQuestionIndex >= quiz.questions.length - 1 &&
        results.style.display === "none") {
        renderResults();
        return
    };
    goTo(currentQuestionIndex + 1)
}

function prevQuestion() {
    const results = document.getElementById("results");

    if (results.style.display !== "none") {
        results.style.display = "none";
        document.querySelector(".question-box").style.display = "";
        renderQuiz();
        return;
    }

    if (currentQuestionIndex <= 0) return;
    goTo(currentQuestionIndex - 1);
}

document.addEventListener("keydown", (e) => {
    if (e.target.tagName === "INPUT" || e.target.tagName === "TEXTAREA") return;

    const key = e.key.toLowerCase();


    // Number = choose
    let index = -1;

    if (/^[1-9]$/.test(key)) {
        index = Number(key) - 1;
    }


    if (index >= 0 && index < optionButtons.length) {
        const button = optionButtons[index];
        if (!button.disabled) {
            handleAnswer(index, button);
        };
        return

    }

    // Reveal answer or go to next question
    if (key === "enter" || key == " ") {
        console.log("handled", key);
        e.preventDefault();

        if (!answerRevealed) {
            revealAnswer();
        } else {
            nextQuestion();
        }
        return;
    }

    // Navigation
    if (key === "arrowright" || key === "l") {
        e.preventDefault();
        nextQuestion();
        return;
    }

    if (key === "arrowleft" || key === "h") {
        e.preventDefault();
        prevQuestion();
        return;
    };
});

// Tap or click to change question (touch control)

questionBox.addEventListener("click", (e) => {
    if (e.target.closest("button, input")) return;

    const rect = questionBox.getBoundingClientRect();
    const x = e.clientX - rect.left;

    if (x > rect.width * 0.7) {
        if (!answerRevealed) {
            revealAnswer();
        } else {
            nextQuestion();
        }
    } else if (x < rect.width * 0.3) {
        prevQuestion();
    }
});


// Change question directly
const questionSelector = document.getElementById("questionSelector");

questionSelector.addEventListener("click", () => {
    questionNumber.focus();
    questionNumber.select();
});

questionNumber.addEventListener("change", () => {
    if (!questionNumber.value) return;

    goTo(Number(questionNumber.value) - 1);
});

function goTo(question_index) {

    // Clamp between first and last question
    question_index = Math.max(
        0,
        Math.min(question_index, quiz.questions.length - 1)
    );

    currentQuestionIndex = question_index

    setStoredQuestionIndex(currentQuestionIndex);

    answerRevealed = false;

    questionNumber.value = currentQuestionIndex + 1;
    renderQuiz();
}

function handleAnswer(index, button) {
    if (index === currentQuestion.correct_index) {

        button.classList.add("correct");
        button.disabled = true;


        if (wrongAnswerCount === 0) {
            questionResults[currentQuestionIndex] = CORRECT;
            saveStats();
        }

        optionButtons.forEach(btn => btn.disabled = true);
    } else {
        button.classList.add("wrong");
        button.disabled = true;

        questionResults[currentQuestionIndex] = WRONG;
        saveStats();

        wrongAnswerCount++;

        if (wrongAnswerCount === currentQuestion.options.length - 1) {
            revealAnswer();
        }
    }
}

function revealAnswer() {
    answerRevealed = true;

    if (questionResults[currentQuestionIndex] === UNANSWERED) {
        questionResults[currentQuestionIndex] = SKIPPED;
        saveStats();
    }
    const currentQuestion = quiz.questions[currentQuestionIndex];
    const optionsContainer = document.getElementById("options");

    // Get all buttons in the current question
    const buttons = optionsContainer.querySelectorAll("button");

    // Highlight the correct answer
    buttons[currentQuestion.correct_index].classList.add("correct");
};

// Download as HTML

function downloadQuizHTML(filename = quiz.title) {
    // Get full document HTML
    const html = "<!DOCTYPE html>\n" + document.documentElement.outerHTML;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();

    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// Timer



function getTimerKey() {
    return `quizTimer_${getStorageKey()}`;
}

function loadTimer() {
    try {
        const data = JSON.parse(
            localStorage.getItem(getTimerKey())
        );

        timerElapsed = data?.elapsed || 0;
        timerStart = data?.start || null;
    } catch {
        timerElapsed = 0;
        timerStart = null;
    }
}

function saveTimer() {
    try {
        localStorage.setItem(
            getTimerKey(),
            JSON.stringify({
                elapsed: timerElapsed,
                start: timerStart
            })
        );
    } catch { }
}

function updateTimer() {
    if (!timerStart) return;

    const elapsed =
        timerElapsed + Math.floor((Date.now() - timerStart) / 1000);

    timer.textContent = formatTime(elapsed);
}

function toggleTimer() {
    timerVisible = !timerVisible;
    timer.classList.toggle("visible", timerVisible);

    if (timerVisible) {
        loadTimer();

        // Start
        if (!timerStart) {
            timerStart = Date.now();
            saveTimer();
        }

        updateTimer();
        timerInterval = setInterval(updateTimer, 1000);

    } else {
        // Pause
        if (timerStart) {
            timerElapsed +=
                Math.floor((Date.now() - timerStart) / 1000);

            timerStart = null;
            saveTimer();
        }

        clearInterval(timerInterval);
        timerInterval = null;
    }
}

// Render results page

function renderResults() {
    const questionBox = document.querySelector(".question-box");
    const results = document.getElementById("results");

    questionBox.style.display = "none";
    results.style.display = "";

    const correct = questionResults.filter(x => x === CORRECT).length;
    const wrong = questionResults.filter(x => x === WRONG).length;
    const unanswered = questionResults.filter(x => x === UNANSWERED).length;
    const skipped = questionResults.filter(x => x === SKIPPED).length;

    const total = quiz.questions.length;
    const answered = correct + wrong;

    const accuracy = answered > 0
        ? (correct / answered) * 100
        : 0;

    const elapsed = timerVisible
        ? timerElapsed + Math.floor((Date.now() - timerStart) / 1000)
        : Math.floor((Date.now() - defaultStartDate) / 1000);


    const styles = getComputedStyle(document.documentElement);
    const chartData = {
        labels: [
            "Correct",
            "Wrong",
            "Unanswered",
            "Skipped"
        ],
        datasets: [{
            label: "Score Chart",
            data: [correct, wrong, unanswered, skipped],
            classNames: ["chart-correct", "chart-wrong", "chart-unanswered", "chart-skipped"]
        }]
    };
    document.getElementById("score").textContent =
        `Score: ${correct}/${wrong + correct}`;

    document.getElementById("accuracy").textContent =
        `Accuracy: ${accuracy.toFixed(1)}%`;

    document.getElementById("correct").textContent =
        `Correct: ${correct}`;

    document.getElementById("wrong").textContent =
        `Wrong: ${wrong}`;

    document.getElementById("unanswered").textContent =
        `Unanswered: ${unanswered}`;

    document.getElementById("skipped").textContent =
        `Skipped: ${skipped}`;

    document.getElementById("time").textContent =
        `Time: ${formatTime(elapsed)}`;

    document.getElementById("averageTime").textContent =
        `Average time per question: ${formatTime(
            Math.floor(elapsed / total)
        )}`;

    createDonutChart(document.getElementById("statsChart"), chartData);
}

function createDonutChart(container, data) {
    const viewSize = 100;
    const center = viewSize / 2;

    const outerRadius = 37.5;
    const innerRadius = 20;
    const midRadius = (outerRadius + innerRadius) / 2;
    const strokeWidth = outerRadius - innerRadius;

    const circumference = 2 * Math.PI * midRadius;

    const values = data.datasets[0].data;
    const classNames = data.datasets[0].classNames;
    const total = values.reduce((sum, v) => sum + v, 0);

    let offset = 0;

    const arcs = values.map((value, i) => {
        if (value === 0 || total === 0) return "";

        const fraction = value / total;
        const dash = fraction * circumference;
        const gap = circumference - dash;

        const circle = `<circle
            class="${classNames[i]}"
            cx="${center}" cy="${center}" r="${midRadius}"
            fill="none"
            stroke-width="${strokeWidth}"
            stroke-dasharray="${dash} ${gap}"
            stroke-dashoffset="${-offset}"
            transform="rotate(-90 ${center} ${center})"
        />`;

        offset += dash;
        return circle;
    }).join("");

    container.innerHTML = `
        <svg viewBox="0 0 ${viewSize} ${viewSize}" preserveAspectRatio="xMidYMid meet" style="width: 100%; height: 100%; display: block;">
            ${arcs}
        </svg>
    `;
}

function formatTime(seconds) {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;

    return `${String(minutes).padStart(2, "0")}:${String(remainingSeconds).padStart(2, "0")}`;
}

function getStatsKey() {
    return `quizStats_${getStorageKey()}`;
}

function loadStats() {
    try {
        const data = JSON.parse(localStorage.getItem(getStatsKey()));

        if (Array.isArray(data?.results)) {
            questionResults = data.results;
        }

        if (data?.startDate) {
            defaultStartDate = data.startDate;
        }
    } catch {
        questionResults = new Array(quiz.questions.length).fill(UNANSWERED);
        defaultStartDate = Date.now();
    }
}

function saveStats() {
    try {
        localStorage.setItem(
            getStatsKey(),
            JSON.stringify({
                results: questionResults,
                startDate: defaultStartDate
            })
        );
    } catch { }
}

function restartQuiz() {

    // Reset question state
    currentQuestionIndex = 0;
    questionNumber.value = 1;
    answerRevealed = false;
    wrongAnswerCount = 0;

    // Reset stats
    questionResults = new Array(quiz.questions.length).fill(UNANSWERED);

    // Reset timer
    clearInterval(timerInterval);
    timerInterval = null;

    timerElapsed = 0;
    timerStart = timerVisible ? Date.now() : null;
    defaultStartDate = Date.now();


    if (timerVisible) {
        updateTimer();
        timerInterval = setInterval(updateTimer, 1000);
    } else {
        timer.textContent = formatTime(0);
    }
    saveTimer();

    // Reset stored question
    setStoredQuestionIndex(0);

    // Return to quiz
    results.style.display = "none";
    questionBox.style.display = "";

    renderQuiz();
}

function confirmRestart() {
    document.getElementById("restart-confirm").style.display = "flex";
}

function cancelRestart() {
    document.getElementById("restart-confirm").style.display = "none";
}

function getStorageKey() {
    // Hash derived from the quiz's content to avoid overlap
    const data = JSON.stringify(quiz);

    let hash = 0;
    for (let i = 0; i < data.length; i++) {
        hash = ((hash << 5) - hash) + data.charCodeAt(i);
        hash |= 0;
    }

    return `currentQuestionIndex_${hash >>> 0}`;
}

function getStoredQuestionIndex() {
    try {
        const index = Number(localStorage.getItem(getStorageKey()));

        if (!Number.isInteger(index)) {
            return 0;
        }

        return Math.max(
            0,
            Math.min(index, quiz.questions.length - 1)
        );

    } catch {
        return 0;
    }
}

function setStoredQuestionIndex(value) {
    try {
        localStorage.setItem(getStorageKey(), String(value));
    } catch (e) {
        // Ignore if storage is unavailable
    }
}


loadMathJax().then(() => {
    if (window.MathJax?.startup?.promise) {
        MathJax.startup.promise.then(renderQuiz);
    } else {
        renderQuiz();
    }
});
"""
