"""
title: QuizUI
author: Axel Chamberland
git_url: https://github.com/axel-chamberland/OpenQuizUI
description: This tool gives an interface for quizzes generated by large language model.
version: 2.0
licence: MIT
"""

from pydantic import BaseModel, Field
from fastapi.responses import HTMLResponse
from difflib import SequenceMatcher
import json
import random


THEMES = {
    "default_light": """
--bg: oklch(100% 0 0);
--btn: oklch(94% 0 0);
--text: oklch(20% 0 0);
--border: oklch(85% 0 0);

--success: #0fff93;
--danger: #ff4545;
--skipped: #ffb800;
--unanswered: #8a8a8a;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "default_dark": """
--bg: oklch(20% 0 0);
--btn: oklch(24% 0 0);
--text: oklch(94% 0 0);
--border: oklch(85% 0 0);

--success: #00ff00;
--danger: #ff0000;
--skipped: #ffcc00;
--unanswered: #999999;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "tokyonight": """
--bg: #1a1b26;
--btn: #242b42;
--text: #c0caf5;
--border: #7aa2f7;

--success: #1abc9c;
--danger: #ff007c;
--skipped: #e0af68;
--unanswered: #565f89;

--correct_bg: color-mix(in srgb, var(--success) 30%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 30%, var(--btn));
""",
    "high_contrast": """
--bg: #000000;
--btn: #111111;
--text: #ffffff;
--border: #ffffff;

--success: #00ff00;
--danger: #ff0000;
--skipped: #ffff00;
--unanswered: #00ffff;

--correct_bg: color-mix(in srgb, var(--success) 40%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 40%, var(--btn));
""",
    "soft_pastel": """
--bg: #fdf6f0;
--btn: #f2e9e4;
--text: #4a4a4a;
--border: #d8cfc4;

--success: #6bbf59;
--danger: #e07a5f;
--skipped: #e6b566;
--unanswered: #a8998e;

--correct_bg: color-mix(in srgb, var(--success) 25%, var(--btn));
--wrong_bg: color-mix(in srgb, var(--danger) 25%, var(--btn));
""",
}


class Tools:
    def __init__(self):
        """Initialize the Tool."""
        self.valves = self.Valves()

    class Valves(BaseModel):
        enable_mathjax: bool = Field(
            default=False,
            description="Disabled by default for privacy and performance. Enable LaTeX/math rendering with MathJax. Requires Internet access to load the MathJax library from a CDN. When disabled or offline, LaTeX expressions are displayed as plain text.",
        )

        dark_mode: int = Field(
            default=-1,
            description="-1: Let browser decide. 0: Light mode. 1: Dark mode",
        )
        light_theme: str = Field(
            default="default_light",
            description="change the dark mode theme to a different theme. to define a new theme, you can add a theme at the top of the code where the templates are. Defaults: default_light, soft_pastel",
        )
        dark_theme: str = Field(
            default="default_dark",
            description="change the dark mode theme to a different theme. to define a new theme, you can add a theme at the top of the code where the templates are. Defaults: default_dark. high_contrast, tokyonight",
        )

    async def generate_quiz(self, title, questions: list[dict]):
        """
        Generate a multiple-choice quiz and display it to the user.

        Args:
            title (str):
                The title of the quiz.

            questions (list[dict]):
                A list of question objects. Each dictionary MUST contain
                these three keys:
                    - "question"    (str)       The question text.
                    - "answer"      (str)       The single CORRECT answer,
                                                 written out in full.
                    - "distractors" (list[str]) 1 or more WRONG answers.
                                                 Do not include the correct
                                                 answer in this list.

                Example of one valid item:
                    {
                        "question": "What is the capital of France?",
                        "answer": "Paris",
                        "distractors": ["Berlin", "Rome", "Madrid"]
                    }

                Write the answer only once, in "answer" — do not also
                repeat it inside "distractors". Do not rename any key.
                Every item must follow this exact structure or the quiz
                will fail to generate.

        Returns:
            Generated quiz accessible to the user,
            or an error message.
        """
        try:
            questions_and_answers, warnings = normalize_questions(questions)

            if not questions_and_answers:
                error_report = "\n".join(f"- {w}" for w in warnings)
                return (
                    "The quiz could not be generated because no valid "
                    "questions could be recovered from 'questions':\n\n"
                    f"{error_report}\n\n"
                    "Please regenerate the JSON. Each item needs 'question' "
                    "(string), 'answer' (string, the correct answer), and "
                    "'distractors' (a list of at least 1 wrong answer)."
                )

            shuffle_options(questions_and_answers)

            quiz = {"title": title, "questions": questions_and_answers}

            # Modify Theme

            option_dark = self.valves.dark_theme
            option_light = self.valves.light_theme

            if self.valves.dark_mode == 0:
                option_dark = option_light
            elif self.valves.dark_mode == 1:
                option_light = option_dark

            dark_theme = THEMES.get(option_dark, THEMES["default_dark"])
            light_theme = THEMES.get(option_light, THEMES["default_light"])

            # Generate quiz
            content = wrap_html(
                quiz, self.valves.enable_mathjax, light_theme, dark_theme
            )
            return HTMLResponse(
                content=content,
                headers={"Content-Disposition": "inline"},
            )

        except Exception as e:
            return f"An unexpected error occurred: {e}"


# =========================
# NORMALIZATION
# =========================

# Accepted synonyms for each field, since weaker models often use a
# slightly different key name than the one requested.
_QUESTION_KEYS = ("question", "q", "prompt", "text")
_ANSWER_KEYS = ("answer", "correct", "correct_answer", "correct_option")
_DISTRACTOR_KEYS = (
    "distractors",
    "wrong_answers",
    "incorrect_answers",
    "wrong_options",
)
_OPTIONS_KEYS = ("options", "choices", "answers", "choices_list")
_INDEX_KEYS = ("correct_index", "answer_index", "index", "correctIndex")


def _first_present(d: dict, keys, expected_type=None):
    for k in keys:
        if k in d:
            v = d[k]
            if expected_type is None or isinstance(v, expected_type):
                return v
    return None


def _best_match_index(answer_text: str, options: list) -> int | None:
    """Find which option the model's free-text answer refers to.

    Tries exact (case-insensitive) match first, then substring match,
    then falls back to the closest fuzzy match so small wording
    differences ("Paris." vs "Paris") don't cause a hard failure.
    """
    if not isinstance(answer_text, str):
        return None

    norm_answer = answer_text.strip().lower().rstrip(".")
    norm_options = [str(o).strip().lower().rstrip(".") for o in options]

    if norm_answer in norm_options:
        return norm_options.index(norm_answer)

    for i, o in enumerate(norm_options):
        if norm_answer in o or o in norm_answer:
            return i

    best_i, best_score = None, 0.0
    for i, o in enumerate(norm_options):
        score = SequenceMatcher(None, norm_answer, o).ratio()
        if score > best_score:
            best_i, best_score = i, score

    return best_i if best_score >= 0.6 else None


def normalize_questions(questions) -> tuple[list[dict], list[str]]:
    """
    Best-effort cleanup of whatever the model produced.

    Returns (normalized_questions, warnings). Items that can't be
    salvaged are skipped (with a warning) rather than aborting the
    whole quiz — one bad question shouldn't sink the other nine.
    """
    warnings: list[str] = []

    if not isinstance(questions, list):
        return [], [
            f"'questions' must be a list of question objects, got "
            f"'{type(questions).__name__}'."
        ]

    normalized = []

    for i, q in enumerate(questions):
        label = f"Question at position {i}"

        if not isinstance(q, dict):
            warnings.append(f"{label} is not an object — skipped.")
            continue

        question_text = _first_present(q, _QUESTION_KEYS)

        if question_text is None:
            warnings.append(f"{label} is missing question text — skipped.")
            continue

        question_text = str(question_text)

        if not question_text.strip():
            warnings.append(f"{label} is missing question text — skipped.")
            continue

        options = None
        correct_index = None

        # --- Preferred path: answer + distractors -------------------
        # No text-matching needed here: we build the option list
        # ourselves, so the correct answer can't fail to line up with
        # itself the way it could when the model had to repeat it
        # verbatim inside an "options" array.
        answer_text = _first_present(q, _ANSWER_KEYS)

        if answer_text is not None:
            answer_text = str(answer_text)

        distractors = _first_present(q, _DISTRACTOR_KEYS, list)

        if answer_text and distractors:
            distractors = [str(d) for d in distractors if str(d).strip()]
            # Guard against the model accidentally repeating the
            # answer inside distractors too (ignoring case/punctuation
            # so "Paris." doesn't slip past "Paris").
            norm_answer = answer_text.strip().lower().rstrip(".")
            distractors = [
                d for d in distractors if d.strip().lower().rstrip(".") != norm_answer
            ]
            if distractors:
                options = [answer_text] + distractors
                correct_index = 0

        if options is None or correct_index is None:
            warnings.append(
                f"{label} ('{question_text[:40]}...') — could not determine "
                f"a valid answer and distractors — skipped."
            )
            continue

        normalized.append(
            {
                "id": q.get("id") or f"q{i + 1}",
                "question": question_text,
                "options": options,
                "correct_index": correct_index,
            }
        )

    return normalized, warnings


# =========================
# QUIZ LOGIC
# =========================


def shuffle_options(questions: list[dict]):

    for question in questions:
        choices = question["options"]

        indices = list(range(len(choices)))
        random.shuffle(indices)

        shuffled_options = []
        new_correct_index = None
        for new_idx, old_idx in enumerate(indices):
            shuffled_options.append(choices[old_idx])
            if old_idx == question["correct_index"]:
                new_correct_index = new_idx

        question["options"] = shuffled_options
        question["correct_index"] = new_correct_index


# =========================
# HTML WRAPPER
# =========================


def wrap_html(quiz, enable_mathjax: bool, light_theme, dark_theme):
    quiz_json = json.dumps(quiz)

    rendered_script = script.replace(
        "__ENABLE_MATHJAX__", "true" if enable_mathjax else "false"
    )

    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Quiz</title>

<style>
{style.format(light_theme=light_theme, dark_theme=dark_theme)}
</style>
</head>

<body>
{svg_icons}
<div class="question-box">
    <div class="title-bar">
        <h1 id="title"></h1>
        <span id="timer">00:00</span>
    </div>
    <div class="navigation-scroll">

        <div id="navigation">

            <button id="prev-button" onclick="prevQuestion()">&lt;</button>

            <div id="question-selector">
                <input id="question-number" type="text" inputmode="numeric" value="1">
                <span class="separator">/</span>
                <span id="question-count">1</span>
            </div>

            <button id="next-button" onclick="nextQuestion()">&gt;</button>

            <button id="reveal-button" onclick="revealAnswer()" aria-label="Reveal answer">
                <svg><use href="#icon-reveal"></use></svg>
            </button>

            <button id="maximize-button" onclick="toggleFullscreen()" aria-label="Fullscreen">
                <svg><use href="#icon-fullscreen"></use></svg>
            </button>

            <button id="download-button" onclick="downloadQuizHTML()" aria-label="Download">
                <svg><use href="#icon-download"></use></svg>
            </button>

            <button id="timer-toggle" onclick="toggleTimer()" aria-label="Timer">
                <svg><use href="#icon-timer"></use></svg>
            </button>

            <button id="editor-button" onclick="openEditor()" aria-label="Editor">
                <svg><use href="#icon-editor"></use></svg>
            </button>

        </div>
    </div>
    <div id="question-scroll">
        <p id="question"></p>
        <div id="options"></div>
    </div>
</div>


<div id="results" style="display: none;">
    <div class=navigation-scroll>
        <div id="results-navigation">
            <button onclick="prevQuestion()">&lt</button>

            <button onclick="toggleFullscreen()" aria-label="Fullscreen">
                <svg><use href="#icon-fullscreen"></use></svg>
            </button>

            <button id="resultsDownloadButton" onclick="downloadQuizHTML()" aria-label="Download">
                <svg><use href="#icon-download"></use></svg>
            </button>
        </div>
    </div>
    <div id="results-scroll">

        <div id="time"></div>
        <div id="averageTime"></div>

        <div class="stat-row">
            <div id="correct"></div>
            <div id="wrong"></div>
        </div>
        <div class="stat-row">
            <div id="skipped"></div>
            <div id="unanswered"></div>
        </div>

        <div class="stat-row">
            <div id="score"></div>
            <div id="accuracy"></div>
        </div>


        <div id="statsChart"></div>

        <button onclick="confirmRestart()">Restart</button>
        <div id="restart-confirm" style="display: none;">
            <span>Restart quiz?</span>
            <button onclick="restartQuiz()">Yes</button>
            <button onclick="cancelRestart()">No</button>
        </div>

    <section class="correction-sheet">
        <h2>Correction</h2>
        <div id="question-corrections"></div>
    </section>
    </div>

</div>


<div id="editor" style="display: none;">
    <h1>Question Editor</h1>
    <div class=navigation-scroll id="editor-navigation">
        <button onclick="saveEdit()">save</button>
        <button onclick="toggleFullscreen()" aria-label="Fullscreen">
            <svg><use href="#icon-fullscreen"></use></svg>
        </button>
        <button onclick="closeEditorConfirm()">close</button>
    </div>
    <div id="editor-close" class="editor-prompt">
        <p id="editor-prompt-message"></p>
        <div class="button-row">
            <button id="editor-prompt-yes">yes</button>
            <button id="editor-prompt-no">no</button>
        </div>
    </div>
    <p>
        <strong>Limitation:</strong>
        Changes are stored in your browser.<br>
        Download the modified quiz as a new HTML file to keep your changes permanently.
    </p>
    <div id="editor-scroll">
        <p><strong>Title:</strong></p>
        <div id="editor-title"></div>
        <p><strong>Question:</strong></p>
        <div id="editor-question"></div>
        <div class="answer-position">
            <p><strong>Answer Position:</strong></p>
            <input type="text" id="editor-answer-number" inputmode="numeric"></input>
        </div>
        <p><strong>Choices:</strong></p>
        <div id="editor-distractors"></div>
    </div>
</div>



<script>
const quiz = {quiz_json};
{rendered_script}
</script>
<script>
{reportHeight}
</script>
</body>
</html>
"""


# =========================
# Height report script
# =========================

reportHeight = """
function reportHeight() {
    // Do not run when in fullscreen
    if (document.fullscreenElement) return;


    const questionBox = document.querySelector(".question-box");
    const results = document.getElementById("results");
    const editor = document.getElementById("editor");

    const visible =
        questionBox.style.display !== "none"
            ? questionBox
            : results.style.display !== "none"
                ? results
                : editor;

    const h = visible.scrollHeight;

    parent.postMessage({ type: "iframe:height", height: h }, "*");
}

window.addEventListener('load', reportHeight);

new ResizeObserver(reportHeight).observe(document.body);
"""

# =========================
# SVG icons
# =========================

svg_icons = """
<svg style="display: none;">
    <symbol id="icon-reveal" viewBox="0 0 24 24">
        <path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12z"/>
        <circle cx="12" cy="12" r="2.5"/>
    </symbol>

    <symbol id="icon-fullscreen" viewBox="0 0 24 24">
        <path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/>
    </symbol>

    <symbol id="icon-download" viewBox="0 0 24 24">
        <path d="M12 3v12m0 0 5-5m-5 5-5-5M4 21h16"/>
    </symbol>

    <symbol id="icon-timer" viewBox="0 0 24 24">
        <circle cx="12" cy="13" r="8"/>
        <path d="M12 9v4l3 2M9 3h6"/>
    </symbol>

    <symbol id="icon-editor" viewBox="0 0 24 24">
        <rect x="5" y="4" width="14" height="17" rx="2"/>
        <path d="M9 3h6v3H9z"/>
        <path d="M8 11h8M8 15h5"/>
    </symbol>
</svg>
"""

#
# =========================
# STYLE
# =========================

style = """
:root {{
    color-scheme: light dark;
{light_theme}
}}

@media (prefers-color-scheme: dark) {{
    :root {{
{dark_theme}
    }}
}}
* {{
    box-sizing: border-box;
    font-family: inherit;
}}
body {{
    background: var(--bg);
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    margin: 0;
}}

:fullscreen body {{
    position: fixed;
    inset: 0;
}}

:fullscreen .question-box,
:fullscreen #results,
:fullscreen #editor {{
    flex: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
}}

:fullscreen .navigation-scroll {{
    flex: 0 0 auto;
    order: 1;
}}

.title-bar {{
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
}}

.title-bar h1 {{
    margin: 0;
}}
.question-box, #results, #editor {{
    display: flex;
    flex-direction: column;
    color: var(--text);
    width: min(800px, 100%);
    padding: 8px;
    height: auto;
}}

#question {{
    margin-bottom: 2em;
    font-size: 1.1rem;
}}

#question-scroll {{
    display: flex;
    flex-direction: column;
    overflow-y: auto;
    min-height: 0;
}}

:fullscreen #question-scroll {{
    flex: 1;
    order: 0;
}}

#options {{
    display: grid;
    grid-template-columns: 1;
    max-width: 100%;
    gap: 0.75rem;
}}

:fullscreen #options {{
    flex: 1;
    min-height: 0;
}}

button {{
    border: 1px solid;
    border-radius: 0.25rem;
    border-color: var(--border);
    background: var(--btn);
    cursor: pointer;
    text-align: center;
    color: var(--text);
    font-size: 1.1em;
}}

button svg {{
    width: 1em;
    height: 1em;
    fill: none;
    stroke: currentColor;
    stroke-width: 2;
    stroke-linecap: round;
    stroke-linejoin: round;
}}

.option{{
    padding: 1rem 3rem 1rem 3rem;
    position: relative;
    text-align: center;
}}
button:disabled {{
    opacity: 0.4;
}}
.option:hover {{
    filter: contrast(1.1);
}}

.option.correct {{
    background: var(--correct_bg);
    border-color: var(--success);
    opacity: 1;
}}

.option.wrong {{
    background: var(--wrong_bg);
    border-color: var(--danger);
    opacity: 1;
}}


.option::after{{
    position: absolute;
    right: 1rem;
    top: 50%;
    transform: translateY(-50%);
    width: 1rem;
    text-align: center;
}}

.option.correct::after {{
    content: " ✓";
    font-weight: bold;
}}

.option.wrong::after {{
    content: " ✗";
    font-weight: bold;
}}
.navigation-scroll {{
    overflow-x: auto;
    overflow-y: hidden;
}}

#navigation, #results-navigation, #editor-navigation {{

    display: flex;
    flex-wrap: nowrap;
    padding: 0.75rem;
    justify-content: center;
    gap: 0.5rem;
    width: min(800px, 100%);
    z-index: 1000;
    border-bottom: 1px solid var(--border);
    margin-bottom: 20px;

    user-select: none;
    -webkit-user-select: none;
}}

#navigation button,
#results-navigation button,
#editor-navigation button {{
    font-size: 2rem;
    display: flex;
    align-items: center;
    justify-content: center;
}}

:fullscreen #navigation,
:fullscreen #results-navigation,
:fullscreen #editor-navigation {{
    margin: 0;
    border: 0;
}}

#navigation button, #results-navigation button, #editor-navigation button {{
    font-size : 2rem;


}}

#reveal-button,
#maximize-button,
#download-button,
#question-selector {{
    flex: 0 0 auto;
    min-width: 2rem;
}}


#prev-button,
#next-button {{
    flex: 1;
    font-size: clamp(1.5rem, 5vw, 2rem);
    max-width: 4rem;
}}

#question-selector {{
    display: flex;
    align-items: center;
    white-space: nowrap;

    background: var(--btn);
    color: var(--text);

    border: 1px solid var(--border);
    border-radius: 0.25rem;

    font-size : 1.1rem;

    gap: 0.2rem;


}}


#question-number {{

    width: 3ch;
    text-align: center;
    font-size: 1.1rem;

    padding: 0;
    margin: 0;
    line-height: 1;

    background: transparent;
    color: var(--text);
    border: none;
    outline: none;

}}


#question-number:focus {{
    outline: none;
    border: none;
}}

#question-count {{
    margin-right: 0.3em;
}}

mjx-container {{
    max-width: 100%;
    overflow-x: auto;
    white-space: normal;
}}

/* Hide timer by default */
#timer {{
    display: none;
    min-width: 4rem;
    font-size: 1.1rem;
    text-align: center;
    font-variant-numeric: tabular-nums;
}}
#timer.visible {{
    display: inline-block;
}}

#correct {{
    color: var(--success);
}}

#wrong {{
    color: var(--danger);
}}

#unanswered {{
    color: var(--unanswered);
}}

#skipped {{
    color: var(--skipped);
}}

.chart-correct   {{ stroke: var(--success); }}
.chart-wrong     {{ stroke: var(--danger); }}
.chart-unanswered{{ stroke: var(--unanswered); }}
.chart-skipped   {{ stroke: var(--skipped); }}


#results-scroll {{
    min-height: 0;
    display: flex;
    flex-direction: column;
    gap: 1rem;
    margin: 0 auto;
    text-align: center;
    overflow-y: auto;
}}

/* When embedded in an iframe */
body.embedded #results-scroll {{
    max-height: 600px;
}}

:fullscreen #results-scroll {{
    flex: 1;
    min-height: 0;
    max-height: none;
    padding: 1rem;
    box-sizing: border-box;
}}

.stat-row {{
    display: flex;
    gap: 1rem;
}}

.stat-row > div {{
    flex: 1;
    padding: 0.5rem;
    border-radius: 0.5rem;
    background: var(--btn);
}}

#statsChart {{
    height: min(50vh, 500px);
    align-self: center;
}}

.correction-sheet {{
    border-top: 1px solid var(--border);
    text-align: left;
}}

.correction-sheet article {{
    padding: 1rem 0;
    border-bottom: 1px solid var(--border);
}}

.correction-sheet h2 {{
    margin-bottom: 1rem;
}}

.correction-sheet h3 {{
    margin-top: 0;
}}

.correction-sheet p {{
    margin: 0.5rem 0;
}}


:fullscreen #editor {{
    flex: 1;
    min-height: 0;
}}


#editor-scroll {{
    display: flex;
    flex-direction: column;
    overflow-y: auto;
    min-height: 0;
}}

:fullscreen #editor-scroll {{
    flex: 1;
    min-height: 0;
    order: 0;
    padding: 1rem;
    box-sizing: border-box;
}}

textarea {{
    color: var(--text);
    background: var(--bg);
    border: 1px solid var(--border);
    font-size: 1em;
    field-sizing: content;
}}

textarea:focus {{
    outline: none;
    border-color: var(--success);
}}

#editor-distractors article {{
    display: flex;
    align-items: center;
    margin-bottom: 16px;
}}

#editor-distractors textarea {{
    width: 80%;
    height: auto;
}}

#editor-distractors .delete-prompt {{
    display: none;
}}


.editor-prompt {{
    display: none;
}}

.editor-prompt.visible {{
    display: block;
}}

.editor-prompt .button-row {{
    display: flex;
    gap: 0.5rem;
}}
.answer-position {{
    display: flex;
    align-items: center;
    gap: 0.5rem;
}}

.answer-position p {{
    margin: 0.5rem 0;
}}

.answer-position input {{
    width: 3ch;
    field-sizing: content;

    color: var(--text);
    background: var(--bg);
    border: 1px solid var(--border);
    font-size: 1em;
    text-align: center;
}}
"""


# =========================
# SCRIPT (Front End)
# =========================

script = r"""
// Try to load math library (WARNING: requires internet)
const ENABLE_MATHJAX = __ENABLE_MATHJAX__;

// Detect if in an iframe (used for better UI support)
if (window.self !== window.top) {
    document.body.classList.add("embedded");
}

let mathReady = false;

let wrongAnswerCount = 0;

let optionButtons = [];
let currentQuestion = null;

let answerRevealed = false;

// Timer
let timerVisible = false;
let timerStart = null;
let timerElapsed = 0;
let timerInterval = null;

// Key for local storage
const quizStorageKey = hashQuiz(quiz);

// Stats
const UNANSWERED = 0;
const CORRECT = 1;
const WRONG = 2;
const SKIPPED = 3;
let questionResults = new Array(quiz.questions.length).fill(UNANSWERED);
let questionAnswers = new Array(quiz.questions.length).fill(null);
let defaultStartDate = Date.now(); // Default start date used if timer was never started
loadStats();

// Question editing
loadQuizEdits();

const timer = document.getElementById("timer");
const questionBox = document.querySelector(".question-box");
const questionText = questionBox.querySelector("#question");
const optionsContainer = document.getElementById("options");
const navigationContainer = questionBox.querySelector("#navigation");
const questionNumber = document.getElementById("question-number");
const results = document.getElementById("results");

// Update title
document.getElementById("title").textContent = quiz.title;

// Update max question count
const questionCount = document.getElementById("question-count");

questionCount.textContent = quiz.questions.length;

let currentQuestionIndex = getStoredQuestionIndex();
questionNumber.value = currentQuestionIndex + 1;

window.MathJax = {
    tex: {
        inlineMath: [
            ["$", "$"],
            ["\\(", "\\)"],
        ],
    },
};

function loadMathJax() {
    return new Promise((resolve) => {
        if (!ENABLE_MATHJAX) {
            mathReady = false;
            resolve(false);
            return;
        }

        const script = document.createElement("script");
        script.src =
            "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js";

        script.onload = () => {
            mathReady = true;
            resolve(true);
        };

        script.onerror = () => {
            mathReady = false;
            resolve(false);
        };

        document.head.appendChild(script);
    });
}

// UI events

function toggleFullscreen() {
    const el = document.documentElement;

    if (!document.fullscreenElement) {
        el.requestFullscreen?.();
    } else {
        document.exitFullscreen?.();
    }
}


document.addEventListener("keydown", (e) => {
    if (e.target.tagName === "INPUT" || e.target.tagName === "TEXTAREA") return;

    const key = e.key.toLowerCase();

    // Number = choose
    let index = -1;

    if (/^[1-9]$/.test(key)) {
        index = Number(key) - 1;
    }

    if (index >= 0 && index < optionButtons.length) {
        const button = optionButtons[index];
        if (!button.disabled) {
            handleAnswer(index, button);
        }
        return;
    }

    // Reveal answer or go to next question
    if (key === "enter" || key == " ") {
        e.preventDefault();

        if (!answerRevealed) {
            revealAnswer();
        } else {
            nextQuestion();
        }
        return;
    }

    // Navigation
    if (key === "arrowright" || key === "l") {
        e.preventDefault();
        nextQuestion();
        return;
    }

    if (key === "arrowleft" || key === "h") {
        e.preventDefault();
        prevQuestion();
        return;
    }
});

// Tap or click to change question (touch control)

questionBox.addEventListener("click", (e) => {
    if (e.target.closest("button, input")) return;

    const rect = questionBox.getBoundingClientRect();
    const x = e.clientX - rect.left;

    if (x > rect.width * 0.7) {
        if (!answerRevealed) {
            revealAnswer();
        } else {
            nextQuestion();
        }
    } else if (x < rect.width * 0.3) {
        prevQuestion();
    }
});

// Helpers

function renderMath(text) {
    if (!text) return "";

    return text.replace(/\$(.+?)\$/g, (match, expr) => {
        if (mathReady && window.MathJax) {
            return match;
        }
        return `<code>${expr}</code>`;
    });
}

function renderInlineMarkdown(text) {
    if (!text) return "";

    // keep <img> tags, but escape the rest
    text = text.replace(/<(?!\/?img\b)[^>]*>/gi, (match) =>
        match.replace(/</g, "&lt;").replace(/>/g, "&gt;"),
    );

    text = text
        .replace(/<(?!\/?img\b)/gi, "&lt;")
        .replace(/\*\*(.*?)\*\*/g, "<b>$1</b>")
        .replace(/\*(.*?)\*/g, "<i>$1</i>")
        .replace(/`([^`]+)`/g, "<code>$1</code>");

    return renderMath(text);
}

function renderMarkdown(text) {
    if (!text) return "";
    return renderInlineMarkdown(text).replace(/\n/g, "<br>");
}

async function renderQuiz() {
    const questionBox = document.querySelector(".question-box");
    const questionText = questionBox.querySelector("#question");
    const optionsContainer = document.getElementById("options");
    const navigationContainer = questionBox.querySelector("#navigation");

    if (!quiz.questions || quiz.questions.length === 0) {
        document.getElementById("question").textContent =
            "No valid questions parsed";
        return;
    }

    // Update question
    questionText.innerHTML = renderMarkdown(
        quiz.questions[currentQuestionIndex].question,
    );

    // Clear and rebuild options
    optionsContainer.innerHTML = "";
    wrongAnswerCount = 0; // Answer button is revealed when user exhausted all options
    optionButtons = [];

    currentQuestion = quiz.questions[currentQuestionIndex];
    currentQuestion.options.forEach((option, index) => {
        const button = document.createElement("button");
        button.innerHTML = renderMarkdown(option);
        button.className = "option";

        optionButtons.push(button);

        button.addEventListener("click", () => {
            handleAnswer(index, button);
        });

        optionsContainer.appendChild(button);
    });
    // Update button states
    const prevButton = navigationContainer.querySelector("#prev-button");
    prevButton.disabled = currentQuestionIndex === 0;

    // Next button is not disabled as it goes to the result screen after last question
    // const nextButton = navigationContainer.querySelector("#next-button");
    // nextButton.disabled = currentQuestionIndex === quiz.questions.length - 1;

    document.getElementById("question-scroll").scrollTop = 0; // reset scroll

    try {
        await MathJax.typesetPromise();
    } catch (err) {
        console.error("MathJax typesetting failed:", err);
    }
}

function nextQuestion() {
    if (
        currentQuestionIndex >= quiz.questions.length - 1 &&
        results.style.display === "none"
    ) {
        renderResults();
        return;
    }
    goTo(currentQuestionIndex + 1);
}

function prevQuestion() {
    const results = document.getElementById("results");

    if (results.style.display !== "none") {
        results.style.display = "none";
        document.querySelector(".question-box").style.display = "";
        renderQuiz();
        return;
    }

    if (currentQuestionIndex <= 0) return;
    goTo(currentQuestionIndex - 1);
}


// Change question directly
const questionSelector = document.getElementById("question-selector");

questionSelector.addEventListener("click", () => {
    questionNumber.focus();
    questionNumber.select();
});

questionNumber.addEventListener("input", () => {
    questionNumber.value = questionNumber.value.replace(/\D/g, "");
});
questionNumber.addEventListener("change", () => {
    if (!questionNumber.value) return;

    goTo(Number(questionNumber.value) - 1);
});

function goTo(question_index) {
    // Clamp between first and last question
    question_index = Math.max(
        0,
        Math.min(question_index, quiz.questions.length - 1),
    );

    currentQuestionIndex = question_index;

    setStoredQuestionIndex(currentQuestionIndex);

    answerRevealed = false;

    questionNumber.value = currentQuestionIndex + 1;
    renderQuiz();
}

function handleAnswer(index, button) {
    questionAnswers[currentQuestionIndex] = index;
    saveStats();
    if (index === currentQuestion.correct_index) {
        button.classList.add("correct");
        button.disabled = true;

        answerRevealed = true;
        if (wrongAnswerCount === 0) {
            questionResults[currentQuestionIndex] = CORRECT;
            saveStats();
        }

        optionButtons.forEach((btn) => (btn.disabled = true));
    } else {
        button.classList.add("wrong");
        button.disabled = true;

        questionResults[currentQuestionIndex] = WRONG;
        saveStats();

        wrongAnswerCount++;

        if (wrongAnswerCount === currentQuestion.options.length - 1) {
            revealAnswer();
        }
    }
}

function revealAnswer() {
    answerRevealed = true;

    if (questionResults[currentQuestionIndex] === UNANSWERED) {
        questionResults[currentQuestionIndex] = SKIPPED;
        saveStats();
    }
    const currentQuestion = quiz.questions[currentQuestionIndex];
    const optionsContainer = document.getElementById("options");

    // Get all buttons in the current question
    const buttons = optionsContainer.querySelectorAll("button");

    // Highlight the correct answer
    buttons[currentQuestion.correct_index].classList.add("correct");
}

// Download as HTML.
function downloadQuizHTML(filename = quiz.title) {
    // Get full document HTML
    let html = "<!DOCTYPE html>\n" + document.documentElement.outerHTML;

    // Replace the quiz content with the local edits
    const quizJSON = JSON.stringify(quiz).replace(/</g, "\\u003c");

    html = html.replace(/const quiz = .*?;/s, `const quiz = ${quizJSON};`);

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();

    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// Timer

function getTimerKey() {
    return `quizTimer_${quizStorageKey}`;
}

function loadTimer() {
    try {
        const data = JSON.parse(localStorage.getItem(getTimerKey()));

        timerElapsed = data?.elapsed || 0;
        timerStart = data?.start || null;
    } catch {
        timerElapsed = 0;
        timerStart = null;
    }
}

function saveTimer() {
    try {
        localStorage.setItem(
            getTimerKey(),
            JSON.stringify({
                elapsed: timerElapsed,
                start: timerStart,
            }),
        );
    } catch { }
}

function updateTimer() {
    if (!timerStart) return;

    const elapsed = timerElapsed + Math.floor((Date.now() - timerStart) / 1000);

    timer.textContent = formatTime(elapsed);
}

function toggleTimer() {
    timerVisible = !timerVisible;
    timer.classList.toggle("visible", timerVisible);

    if (timerVisible) {
        loadTimer();

        // Start
        if (!timerStart) {
            timerStart = Date.now();
            saveTimer();
        }

        updateTimer();
        timerInterval = setInterval(updateTimer, 1000);
    } else {
        // Pause
        if (timerStart) {
            timerElapsed += Math.floor((Date.now() - timerStart) / 1000);

            timerStart = null;
            saveTimer();
        }

        clearInterval(timerInterval);
        timerInterval = null;
    }
}

// Render results page

async function renderResults() {
    const questionBox = document.querySelector(".question-box");
    const results = document.getElementById("results");

    questionBox.style.display = "none";
    results.style.display = "";

    const correct = questionResults.filter((x) => x === CORRECT).length;
    const wrong = questionResults.filter((x) => x === WRONG).length;
    const unanswered = questionResults.filter((x) => x === UNANSWERED).length;
    const skipped = questionResults.filter((x) => x === SKIPPED).length;

    const total = quiz.questions.length;
    const answered = correct + wrong;

    const accuracy = answered > 0 ? (correct / answered) * 100 : 0;

    const elapsed = timerVisible
        ? timerElapsed + Math.floor((Date.now() - timerStart) / 1000)
        : Math.floor((Date.now() - defaultStartDate) / 1000);

    const chartData = {
        labels: ["Correct", "Wrong", "Unanswered", "Skipped"],
        datasets: [
            {
                label: "Score Chart",
                data: [correct, wrong, unanswered, skipped],
                classNames: [
                    "chart-correct",
                    "chart-wrong",
                    "chart-unanswered",
                    "chart-skipped",
                ],
            },
        ],
    };
    document.getElementById("score").textContent =
        `Score: ${correct}/${wrong + correct}`;

    document.getElementById("accuracy").textContent =
        `Accuracy: ${accuracy.toFixed(1)}%`;

    document.getElementById("correct").textContent = `Correct: ${correct}`;

    document.getElementById("wrong").textContent = `Wrong: ${wrong}`;

    document.getElementById("unanswered").textContent =
        `Unanswered: ${unanswered}`;

    document.getElementById("skipped").textContent = `Skipped: ${skipped}`;

    document.getElementById("time").textContent =
        `Time: ${formatTime(elapsed)}`;

    document.getElementById("averageTime").textContent =
        `Average time per question: ${formatTime(Math.floor(elapsed / total))}`;

    createDonutChart(document.getElementById("statsChart"), chartData);
    showCorrectionSheet();

    if (mathReady && window.MathJax) {
        try {
            await MathJax.typesetPromise([
                document.getElementById("question-corrections"),
            ]);
        } catch (err) {
            console.error("MathJax typesetting failed:", err);
        }
    }
}

function createDonutChart(container, data) {
    const viewSize = 100;
    const center = viewSize / 2;

    const outerRadius = 37.5;
    const innerRadius = 20;
    const midRadius = (outerRadius + innerRadius) / 2;
    const strokeWidth = outerRadius - innerRadius;

    const circumference = 2 * Math.PI * midRadius;

    const values = data.datasets[0].data;
    const classNames = data.datasets[0].classNames;
    const total = values.reduce((sum, v) => sum + v, 0);

    let offset = 0;

    const arcs = values
        .map((value, i) => {
            if (value === 0 || total === 0) return "";

            const fraction = value / total;
            const dash = fraction * circumference;
            const gap = circumference - dash;

            const circle = `<circle
class="${classNames[i]}"
cx="${center}" cy="${center}" r="${midRadius}"
fill="none"
stroke-width="${strokeWidth}"
stroke-dasharray="${dash} ${gap}"
stroke-dashoffset="${-offset}"
transform="rotate(-90 ${center} ${center})"
/>`;

            offset += dash;
            return circle;
        })
        .join("");

    container.innerHTML = `
<svg viewBox="0 0 ${viewSize} ${viewSize}" preserveAspectRatio="xMidYMid meet" style="width: 100%; height: 100%; display: block;">
    ${arcs}
</svg>
`;
}

function formatTime(seconds) {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;

    return `${String(minutes).padStart(2, "0")}:${String(remainingSeconds).padStart(2, "0")}`;
}

function getStatsKey() {
    return `quizStats_${quizStorageKey}`;
}

function loadStats() {
    try {
        const data = JSON.parse(localStorage.getItem(getStatsKey()));

        if (Array.isArray(data?.results)) {
            questionResults = data.results;
        }

        if (Array.isArray(data?.answers)) {
            questionAnswers = data.answers;
        }

        if (data?.startDate) {
            defaultStartDate = data.startDate;
        }
    } catch {
        questionResults = new Array(quiz.questions.length).fill(UNANSWERED);
        questionAnswers = new Array(quiz.questions.length).fill(null);
        defaultStartDate = Date.now();
    }
}

function saveStats() {
    try {
        localStorage.setItem(
            getStatsKey(),
            JSON.stringify({
                results: questionResults,
                answers: questionAnswers,
                startDate: defaultStartDate,
            }),
        );
    } catch { }
}

function restartQuiz() {
    // Reset question state
    currentQuestionIndex = 0;
    questionNumber.value = 1;
    answerRevealed = false;
    wrongAnswerCount = 0;

    // Reset stats
    questionResults = new Array(quiz.questions.length).fill(UNANSWERED);
    questionAnswers = new Array(quiz.questions.length).fill(null);
    document.getElementById("question-corrections").innerHTML = "";

    // Reset timer
    clearInterval(timerInterval);
    timerInterval = null;

    timerElapsed = 0;
    timerStart = timerVisible ? Date.now() : null;
    defaultStartDate = Date.now();

    if (timerVisible) {
        updateTimer();
        timerInterval = setInterval(updateTimer, 1000);
    } else {
        timer.textContent = formatTime(0);
    }
    saveTimer();

    // Reset stored question
    setStoredQuestionIndex(0);

    // Return to quiz
    results.style.display = "none";
    questionBox.style.display = "";

    document.getElementById("restart-confirm").style.display = "none";

    renderQuiz();
}

function confirmRestart() {
    document.getElementById("restart-confirm").style.display = "flex";
}

function cancelRestart() {
    document.getElementById("restart-confirm").style.display = "none";
}

function showCorrectionSheet() {
    const container = document.getElementById("question-corrections");
    const questions = quiz.questions;

    container.innerHTML = "";

    for (let index = 0; index < questions.length; index++) {
        const question = questions[index];

        const correctAnswer = question.options[question.correct_index];

        const userIndex = questionAnswers[index];

        const userAnswer =
            questionResults[index] === SKIPPED
                ? "Skipped"
                : userIndex !== null
                    ? question.options[userIndex]
                    : "Unanswered";

        const article = document.createElement("article");

        article.innerHTML = `
<h3>Question ${index + 1}</h3>

<p>${renderMarkdown(question.question)}</p>

<p>
    <strong>Your answer:</strong>
    ${renderMarkdown(userAnswer)}
</p>

<p>
    <strong>Correct answer:</strong>
    ${renderMarkdown(correctAnswer)}
</p>
`;

        container.appendChild(article);
    }
}

// Editor UI Functions

document
    .getElementById("editor-answer-number")
    .addEventListener("input", (e) => {
        e.target.value = e.target.value.replace(/\D/g, "");
    });

function openEditor() {
    const questionBox = document.querySelector(".question-box");
    const editor = document.getElementById("editor");
    const prompt = document.getElementById("editor-close");

    prompt.classList.remove("visible");

    questionBox.style.display = "none";
    editor.style.display = "";

    const titleField = document.getElementById("editor-title");
    const questionField = document.getElementById("editor-question");
    const editorAnswer = document.getElementById("editor-answer-number");
    const optionsContainer = document.getElementById("editor-distractors");

    const question = quiz.questions[currentQuestionIndex];

    // Set initial values
    titleField.innerHTML = `<textarea>${quiz.title}</textarea>`;
    questionField.innerHTML = `<textarea>${question.question}</textarea>`;
    editorAnswer.value = question.correct_index + 1;

    optionsContainer.innerHTML = "";

    question.options.forEach((option) => {
        optionsContainer.appendChild(addEditorOption(option));
    });
}

function addEditorOption(value) {
    const article = document.createElement("article");

    const textarea = document.createElement("textarea");
    textarea.value = value;

    const insertBtn = document.createElement("button");
    insertBtn.textContent = "+";
    insertBtn.onclick = () => {
        article.after(addEditorOption(""));
    };

    const deleteBtn = document.createElement("button");
    deleteBtn.textContent = "⌦";

    const promptDiv = document.createElement("div");
    promptDiv.className = "delete-prompt";

    const confirmBtn = document.createElement("button");
    confirmBtn.textContent = "Confirm";
    confirmBtn.onclick = () => article.remove();

    const cancelBtn = document.createElement("button");
    cancelBtn.textContent = "Cancel";
    cancelBtn.onclick = () => {
        promptDiv.style.display = "none";
    };

    deleteBtn.onclick = () => {
        promptDiv.style.display = "flex";
    };

    promptDiv.appendChild(confirmBtn);
    promptDiv.appendChild(cancelBtn);

    article.appendChild(insertBtn);
    article.appendChild(deleteBtn);
    article.appendChild(promptDiv);
    article.appendChild(textarea);

    return article;
}

function showEditorPrompt(
    message,
    onYes = null,
    onNo = null,
    yesText = "yes",
    noText = "no",
) {
    const prompt = document.getElementById("editor-close");
    const messageElement = document.getElementById("editor-prompt-message");
    const yesButton = document.getElementById("editor-prompt-yes");
    const noButton = document.getElementById("editor-prompt-no");
    messageElement.textContent = message;
    yesButton.textContent = yesText;
    noButton.textContent = noText;
    yesButton.style.display = "";
    noButton.style.display = "";
    yesButton.onclick = () => {
        prompt.classList.remove("visible");
        if (onYes) onYes();
    };
    noButton.onclick = () => {
        prompt.classList.remove("visible");
        if (onNo) onNo();
    };
    prompt.classList.add("visible");
}

function showEditorAlert(message) {
    const prompt = document.getElementById("editor-close");
    const messageElement = document.getElementById("editor-prompt-message");
    const yesButton = document.getElementById("editor-prompt-yes");
    const noButton = document.getElementById("editor-prompt-no");
    messageElement.textContent = message;
    yesButton.textContent = "OK";
    yesButton.style.display = "";
    noButton.style.display = "none";
    yesButton.onclick = () => {
        prompt.classList.remove("visible");
    };
    prompt.classList.add("visible");
}

// Returns false if the selected answer index does not exist in the DOM anymore
function validateAnswerIndex() {
    const answerInput = document.querySelector("#editor-answer-number");

    const val = parseInt(answerInput.value) - 1;

    const optionsContainer = document.getElementById("editor-distractors");
    const options = optionsContainer.querySelectorAll("article");

    if (val < 0 || val >= options.length) {
        answerInput.classList.add("input-error");
        showEditorAlert("Invalid Index: The selected option no longer exists.");
        return false;
    }

    return true;
}

function closeEditorConfirm() {
    showEditorPrompt(
        "Exit? Unsaved changes will be lost.",
        closeEditor,
        null,
        "yes",
        "no",
    );
}

function saveEdit() {
    if (!validateAnswerIndex()) {
        return;
    }

    // Extract data from DOM
    const newTitleText = document.querySelector("#editor-title textarea").value;
    const newQuestionText = document.querySelector(
        "#editor-question textarea",
    ).value;
    const newIndex =
        parseInt(document.querySelector("#editor-answer-number").value) - 1;
    const optionsContainer = document.getElementById("editor-distractors");
    const updatedOptions = Array.from(
        optionsContainer.querySelectorAll("textarea"),
    ).map((ta) => ta.value);

    // Track whether the title was changed
    const titleChanged = quiz.title !== newTitleText;
    quiz.title = newTitleText;
    document.getElementById("title").textContent = newTitleText;

    // Update global state
    quiz.questions[currentQuestionIndex].question = newQuestionText;
    quiz.questions[currentQuestionIndex].correct_index = newIndex;
    quiz.questions[currentQuestionIndex].options = updatedOptions;

    // Persist the actual changes (locally)
    if (saveLocalEdit(currentQuestionIndex, titleChanged)) {
        showEditorAlert("Changes saved.");
    }
}

function closeEditor() {
    const questionBox = document.querySelector(".question-box");
    const editor = document.getElementById("editor");
    const prompt = document.getElementById("editor-close");

    prompt.classList.remove("visible");

    editor.style.display = "none";

    // Reset UI state
    const options = document.getElementById("editor-distractors");
    options.innerHTML = "";

    questionBox.style.display = "";

    renderQuiz();
}

function getQuizEditsKey() {
    return `quizEdits_${quizStorageKey}`;
}

function saveLocalEdit(index, titleChanged) {
    const key = getQuizEditsKey();

    let edits = {};

    try {
        edits = JSON.parse(localStorage.getItem(key)) || {};
    } catch {
        edits = {};
    }

    if (titleChanged) {
        edits.title = quiz.title;
    }

    edits[index] = quiz.questions[index];

    try {
        localStorage.setItem(key, JSON.stringify(edits));
        console.log("Saved edit:", key, edits);
        return true;
    } catch (e) {
        console.error("Failed to save edit:", e);
        return false;
    }
}

function loadQuizEdits() {
    const key = getQuizEditsKey();

    try {
        const edits = JSON.parse(localStorage.getItem(key));

        if (!edits) {
            return;
        }

        if (edits.title !== undefined) {
            quiz.title = edits.title;
        }

        // Load edited questions
        for (const [index, question] of Object.entries(edits)) {
            const i = Number(index);
            if (Number.isInteger(i) && i >= 0 && i < quiz.questions.length) {
                quiz.questions[i] = question;
            }
        }
    } catch (e) {
        console.error("Failed to load quiz edits:", e);
    }
}

function hashQuiz(quiz) {
    // Hash derived from the quiz's content to avoid overlap
    const data = JSON.stringify(quiz);

    let hash = 0;
    for (let i = 0; i < data.length; i++) {
        hash = (hash << 5) - hash + data.charCodeAt(i);
        hash |= 0;
    }

    return `currentQuestionIndex_${hash >>> 0}`;
}

function getStoredQuestionIndex() {
    try {
        const index = Number(
            localStorage.getItem(`currentQuestionIndex_${quizStorageKey}`),
        );

        if (!Number.isInteger(index)) {
            return 0;
        }

        return Math.max(0, Math.min(index, quiz.questions.length - 1));
    } catch {
        return 0;
    }
}

function setStoredQuestionIndex(value) {
    try {
        localStorage.setItem(
            `currentQuestionIndex_${quizStorageKey}`,
            String(value),
        );
    } catch (e) {
        // Ignore if storage is unavailable
    }
}

loadMathJax().then(() => {
    if (window.MathJax?.startup?.promise) {
        MathJax.startup.promise.then(renderQuiz);
    } else {
        renderQuiz();
    }
});
"""
